# Generated by Django 3.2.5 on 2021-07-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='surname',
        ),
    ]
