# Generated by Django 3.2.5 on 2021-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='case_paper',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cadre',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
